# File auto-generated oleh Katalog Koleksi Pribadi (BST).
# Data dummy untuk demo & testing. Tiap item = 1 node binary search tree,
# key = judul. Urutan list = urutan penyisipan (menentukan bentuk pohon).
# Sengaja diselang-seling antar tipe supaya pohon bercabang ke kiri & kanan.

koleksi = [
    {"judul": "Yellow",                   "tipe": "Musik", "data": {"durasi": "4:29", "tahun": 2000}},
    {"judul": "Interstellar",             "tipe": "Film",  "data": {"tahun": 2014, "rating": 8.6}},
    {"judul": "Skyrim",                   "tipe": "Game",  "data": {"rating": 9.0, "jam_main": 120}},
    {"judul": "Laskar Pelangi",           "tipe": "Buku",  "data": {"tahun": 2005, "halaman": 533}},
    {"judul": "Fix You",                  "tipe": "Musik", "data": {"durasi": "4:55", "tahun": 2005}},
    {"judul": "Inception",                "tipe": "Film",  "data": {"tahun": 2010, "rating": 8.8}},
    {"judul": "The Witcher 3",            "tipe": "Game",  "data": {"rating": 9.5, "jam_main": 180}},
    {"judul": "Bumi Manusia",             "tipe": "Buku",  "data": {"tahun": 1980, "halaman": 535}},
    {"judul": "Viva La Vida",             "tipe": "Musik", "data": {"durasi": "4:01", "tahun": 2008}},
    {"judul": "Dune",                     "tipe": "Film",  "data": {"tahun": 2021, "rating": 8.0}},
    {"judul": "Elden Ring",               "tipe": "Game",  "data": {"rating": 9.6, "jam_main": 95}},
    {"judul": "Atomic Habits",            "tipe": "Buku",  "data": {"tahun": 2018, "halaman": 320}},
    {"judul": "Anti-Hero",                "tipe": "Musik", "data": {"durasi": "3:20", "tahun": 2022}},
    {"judul": "John Wick",                "tipe": "Film",  "data": {"tahun": 2014, "rating": 7.4}},
    {"judul": "Counter-Strike 2",         "tipe": "Game",  "data": {"rating": 8.0, "jam_main": 250}},
    {"judul": "Sapiens",                  "tipe": "Buku",  "data": {"tahun": 2011, "halaman": 443}},
    {"judul": "Cruel Summer",             "tipe": "Musik", "data": {"durasi": "2:58", "tahun": 2019}},
    {"judul": "Mad Max: Fury Road",       "tipe": "Film",  "data": {"tahun": 2015, "rating": 8.1}},
    {"judul": "Valorant",                 "tipe": "Game",  "data": {"rating": 8.2, "jam_main": 80}},
    {"judul": "Norwegian Wood",           "tipe": "Buku",  "data": {"tahun": 1987, "halaman": 296}},
    {"judul": "Bohemian Rhapsody",        "tipe": "Musik", "data": {"durasi": "5:55", "tahun": 1975}},
    {"judul": "Forrest Gump",             "tipe": "Film",  "data": {"tahun": 1994, "rating": 8.8}},
    {"judul": "God of War Ragnarok",      "tipe": "Game",  "data": {"rating": 9.4, "jam_main": 45}},
    {"judul": "1984",                     "tipe": "Buku",  "data": {"tahun": 1949, "halaman": 328}},
    {"judul": "We Will Rock You",         "tipe": "Musik", "data": {"durasi": "2:02", "tahun": 1977}},
    {"judul": "The Shawshank Redemption", "tipe": "Film",  "data": {"tahun": 1994, "rating": 9.3}},
    {"judul": "The Last of Us",           "tipe": "Game",  "data": {"rating": 9.5, "jam_main": 30}},
    {"judul": "The 7 Habits",             "tipe": "Buku",  "data": {"tahun": 1989, "halaman": 372}},
    {"judul": "Dynamite",                 "tipe": "Musik", "data": {"durasi": "3:19", "tahun": 2020}},
    {"judul": "Spirited Away",            "tipe": "Film",  "data": {"tahun": 2001, "rating": 8.6}},
    {"judul": "Breath of the Wild",       "tipe": "Game",  "data": {"rating": 9.7, "jam_main": 110}},
    {"judul": "One Piece Vol. 1",         "tipe": "Buku",  "data": {"tahun": 1997, "halaman": 216}},
    {"judul": "Butter",                   "tipe": "Musik", "data": {"durasi": "2:44", "tahun": 2021}},
    {"judul": "Coco",                     "tipe": "Film",  "data": {"tahun": 2017, "rating": 8.4}},
    {"judul": "Tears of the Kingdom",     "tipe": "Game",  "data": {"rating": 9.6, "jam_main": 130}},
    {"judul": "Hati-Hati di Jalan",       "tipe": "Musik", "data": {"durasi": "5:34", "tahun": 2022}},
    {"judul": "Mobile Legends",           "tipe": "Game",  "data": {"rating": 7.5, "jam_main": 200}},
    {"judul": "Monokrom",                 "tipe": "Musik", "data": {"durasi": "4:08", "tahun": 2016}},
]
