# File auto-generated oleh Pemandu Pesan Menu (pohon keputusan).
# Struktur pohon biner: tiap node punya cabang 'ya' & 'tidak'.

menu = {   'teks': 'makanan/minuman',
    'harga': None,
    'deskripsi': '',
    'label_ya': 'makanan',
    'label_tidak': 'minuman',
    'ya': {   'teks': 'nasi/mie',
              'harga': None,
              'deskripsi': '',
              'label_ya': 'nasi',
              'label_tidak': 'mie',
              'ya': {   'teks': 'nasi goreng',
                        'harga': 20000,
                        'deskripsi': '',
                        'ya': None,
                        'tidak': None},
              'tidak': {   'teks': 'goreng/rebus',
                           'harga': None,
                           'deskripsi': '',
                           'label_ya': 'goreng',
                           'label_tidak': 'rebus',
                           'ya': {   'teks': 'mie goreng',
                                     'harga': 20000,
                                     'deskripsi': '',
                                     'ya': None,
                                     'tidak': None},
                           'tidak': {   'teks': 'mie rebus',
                                        'harga': 20000,
                                        'deskripsi': '',
                                        'ya': None,
                                        'tidak': None}}},
    'tidak': {   'teks': 'ice/hot',
                 'harga': None,
                 'deskripsi': '',
                 'label_ya': 'ice',
                 'label_tidak': 'hot',
                 'ya': {   'teks': 'es teh',
                           'harga': 5000,
                           'deskripsi': '',
                           'ya': None,
                           'tidak': None},
                 'tidak': {   'teks': 'teh hangat',
                              'harga': 4000,
                              'deskripsi': '',
                              'ya': None,
                              'tidak': None}}}
